version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/music-service-api
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
          DATABASE_URL: "postgres://root:circleci_test@localhost:5432/music_api_test"
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: music-service-api-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: music-service-api-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load


      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
