# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fbad9dde6208e23d23dea9512c71949fa35f7cc8dce0ea11705010848612982c4f65717bcde84b4f5a65b6234a6f4d26795aedd96fdb8a13a8261f6f7c57c6af

test:
  secret_key_base: 231d76f332f7270b8d5a322f0581fe6727ce4f8623ba1a83c8064c0cfe31735224dfd45544bf38f5742d3e76e48600c78eed5f783c7fab286167524bb1933eb7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
